# Make Xosera Boing program for rosco_m68k
#
# vim: set noet ts=8 sw=8
# Copyright (c) 2022 Thomas Jager
# MIT LICENSE

# location of xosera_m68k_api
XOSERA_M68K_API?=../xosera_m68k_api

# use generic common make rules for Xosera + rosco_m68k build
include $(XOSERA_M68K_API)/common_xosera_m68k.mk

all: $(BINARY) $(DISASM)
