// Note: This header shared between C and CopAsm

#define VRAM_AUDIO_BASE  0x0080
#define VRAM_SILENCE_LEN 0x0001
#define VRAM_BASE_A      0x4000
#define VRAM_BASE_B      0xA000
#define VRAM_BASE_BLANK  0xB800
#define VRAM_BASE_BALL   0xBC00
#define TILE_BASE_B      0xC000

#define WIDTH  640
#define HEIGHT 480

#define WIDTH_A  (WIDTH/2)
#define HEIGHT_A (HEIGHT/2)
#define WIDTH_B  (WIDTH/1)
#define HEIGHT_B (HEIGHT/1)

#define TILE_WIDTH_B  8
#define TILE_HEIGHT_B 8

#define PIXELS_PER_WORD_A 8
#define PIXELS_PER_WORD_B 4

#define COLS_PER_WORD_A 8
#define ROWS_PER_WORD_A 1
#define COLS_PER_WORD_B TILE_WIDTH_B
#define ROWS_PER_WORD_B TILE_HEIGHT_B

#define WIDTH_WORDS_A  (WIDTH_A/COLS_PER_WORD_A)
#define HEIGHT_WORDS_A (HEIGHT_A/ROWS_PER_WORD_A)
#define WIDTH_WORDS_B  (WIDTH_B/COLS_PER_WORD_B)
#define HEIGHT_WORDS_B (HEIGHT_B/ROWS_PER_WORD_B)

#define BALL_BITMAP_WIDTH  256
#define BALL_BITMAP_HEIGHT 256

#define BALL_TILES_WIDTH  (BALL_BITMAP_WIDTH/TILE_WIDTH_B)
#define BALL_TILES_HEIGHT (BALL_BITMAP_WIDTH/TILE_HEIGHT_B)

#define SHADOW_OFFSET_X 36
#define SHADOW_OFFSET_Y 0

#define BALL_SHIFT_X (-SHADOW_OFFSET_X/2)
#define BALL_SHIFT_Y (-SHADOW_OFFSET_Y/2)

#define BALL_CENTER_X (BALL_BITMAP_WIDTH/2+BALL_SHIFT_X)
#define BALL_CENTER_Y (BALL_BITMAP_HEIGHT/2+BALL_SHIFT_Y)

#define BALL_RADIUS 80
