// Native, not m68k!
//
#include <stdio.h>
#include "../pt_mod.h"

int main(void) {
    FILE *f = fopen("xosera_freq.h", "w");

    if (!f) {
        printf("Failed to open file; Bailing...\n");
    } else {
        fprintf(f, "// Autogenerated; Do not edit\n\n");

        fprintf(f, "#ifdef NTSC\n");
        fprintf(f, "static uint16_t XOSERA_FREQ[] = {\n    ");

        for (int i = 0; i < 1712; i++) {
            if (i > 0 && i % 20 == 0) {
                fprintf(f, "\n    ");
            }

            fprintf(f, "%d, ", (uint16_t)PtXoseraPeriodNTSC(i));
        }

        fprintf(f, "\n};\n");
        fprintf(f, "#else\n");
        fprintf(f, "static uint16_t XOSERA_FREQ[] = {\n    ");

        for (int i = 0; i < 1712; i++) {
            if (i > 0 && i % 20 == 0) {
                fprintf(f, "\n    ");
            }

            fprintf(f, "%d, ", (uint16_t)PtXoseraPeriodPAL(i));
        }

        fprintf(f, "\n};\n");
        fprintf(f, "#endif\n\n");
        fclose(f);
    }
}



